jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin"

  # Security Realm for user authentication
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"
        - id: "developer"
          password: "developer"
        - id: "viewer"
          password: "viewer"

  # Authorization Strategy
  authorizationStrategy:
    projectMatrix:
      entries:
        - user:
            name: admin
            permissions:
              - Overall/Administer
        - user:
            name: developer
            permissions:
              - Overall/Read
              - Job/Build
        - user:
            name: viewer
            permissions:
              - Overall/Read

# Tool Configuration
tool:
  git:
    installations:
      - name: "Default"
        home: "/usr/bin/git"
  maven:
    installations:
      - name: maven3
        properties:
          - installSource:
              installers:
                - maven:
                    id: "3.8.4"

# Sample Job Configuration
jobs:
  - script: >
      pipelineJob('example-pipeline-job') {
        definition {
          cps {
            script('''
              pipeline {
                agent any

                tools {
                  git 'Default' // Use the Git tool configured above
                  maven 'maven3' // Use the Maven tool configured above
                }

                stages {
                  stage('Checkout Code') {
                    steps {
                      git branch: 'main', url: 'https://github.com/your-repo/your-project.git'
                    }
                  }

                  stage('Build') {
                    steps {
                      sh 'mvn clean install'
                    }
                  }

                  stage('Test') {
                    steps {
                      sh 'mvn test'
                    }
                  }

                  stage('Deploy') {
                    steps {
                      echo 'Deploying...'
                    }
                  }
                }

                post {
                  always {
                    junit '**/target/surefire-reports/*.xml' // Publish JUnit test results
                  }
                }
              }
            ''')
          }
        }
      }