jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin"

  # Security Realm for user authentication
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"

  # Authorization Strategy
  authorizationStrategy:
    projectMatrix:
      entries:
        - user:
            name: admin
            permissions:
              - Overall/Administer
        - user:
            name: developer
            permissions:
              - Overall/Read
              - Job/Build
        - user:
            name: viewer
            permissions:
              - Overall/Read

# Tool Configuration
tool:
  git:
    installations:
      - name: "Default"
        home: "/usr/bin/git" # Git executable path on Linux
  maven:
    installations:
      - name: maven3
        properties:
          - installSource:
              installers:
                - maven:
                    id: "3.8.4"
  allure:
    installations:
      - name: "allure" # Name of the Allure tool
        properties:
          - installSource:
              installers:
                - commandline:
                    command: "/usr/local/bin/allure" # Allure executable path on Linux
                    label: "allure"

# Job Configuration with Groovy Script Loaded
jobs:
  - script: >
      pipelineJob('example-pipeline-job') {
        definition {
          cps {
            script('''
              pipeline {
                agent any

                tools {
                  allure 'allure' // Use the Allure tool configured above
                }

                stages {
                  stage('Test Execution') {
                    steps {
                      script {
                        // For Linux
                        sh 'mvn clean test -Pweb-execution -Dsuite=local -Dtarget=local -Dheadless=false -Dbrowser=chrome -Dauto.report=false'
                      }
                    }
                  }
                }

                post {
                  always {
                    // Generate and publish Allure report
                    allure([
                      includeProperties: false,
                      jdk: '', // Optionally, specify JDK if required
                      results: [[path: 'target/allure-results']] // Path to Allure results folder
                    ])
                  }
                }
              }
            ''')
          }
        }
      }
