jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin"

  # Security Realm for user authentication
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"
        - id: "developer"
          password: "developer"
        - id: "viewer"
          password: "viewer"

  # Authorization Strategy
  authorizationStrategy:
    projectMatrix:
      entries:
        - user:
            name: admin
            permissions:
              - Overall/Administer
        - user:
            name: developer
            permissions:
              - Overall/Read
              - Job/Build
        - user:
            name: viewer
            permissions:
              - Overall/Read

# Tool Configuration
tool:
  maven:
    installations:
      - name: maven3
        properties:
          - installSource:
              installers:
                - maven:
                    id: "3.8.4"

# Sample Job Configuration
jobs:
  - script: >
      pipelineJob('example-pipeline-job') {
        definition {
          cps {
            script('''
              pipeline {
                agent any

                stages {
                  stage('Test Execution') {
                    steps {
                      script {
                        // Clean the target folder and run tests depending on the operating system
                        if (isUnix()) {
                          // For Unix-based systems, use Maven Wrapper
                          sh './mvnw clean test -Pweb-execution -Dsuite=local -Dtarget=local -Dheadless=false -Dbrowser=chrome'
                        } else {
                          // For Windows, use Maven Wrapper with .cmd
                          bat 'mvnw.cmd clean test -Pweb-execution -Dsuite=local -Dtarget=local -Dheadless=false -Dbrowser=chrome'
                        }
                      }
                    }
                  }
                }

                post {
                  always {
                    // Publish Allure report as HTML using the HTML Publisher plugin
                    publishHTML(target: [
                      reportDir: 'target/allure-report', // Path to Allure report folder
                      reportFiles: 'index.html', // Main file in the Allure report
                      reportName: 'Report', // Name of the report in Jenkins UI
                      alwaysLinkToLastBuild: true
                    ])
                  }
                }
              }
            ''')
          }
        }
      }